[tool.poetry]
name = "pyvenv"
version = "0.1.0"
description = ""
authors = ["Arunachalam"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
notebook = "^7.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
